CREATE SCHEMA IF NOT EXISTS plataforma;
CREATE SCHEMA IF NOT EXISTS sabor_familia;
CREATE SCHEMA IF NOT EXISTS lista_compras;
CREATE SCHEMA IF NOT EXISTS remember;
CREATE SCHEMA IF NOT EXISTS care_hub;
CREATE SCHEMA IF NOT EXISTS care_keeper;
CREATE SCHEMA IF NOT EXISTS dose_certa;
CREATE SCHEMA IF NOT EXISTS elden_care;